// pdfExport.js
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const COMPANY = "Nova Geo Resources LLP";
const TAGLINE = "Ball Mill Processing Plant — Telangana";

// jsPDF's built-in fonts have no ₹ glyph — it renders as garbage (that
// superscript "1") and miscalculates string width, which is what was
// cutting the Amount/NBV columns short. Swap it for plain text first.
function rupeeSafe(val) {
  if (val == null) return val;
  return String(val).replace(/\u20B9/g, "Rs. ");
}

export function exportStatementPDF({ title, subtitle, summary = [], columns, rows, fileName }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(COMPANY, 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(TAGLINE, 40, y + 14);
  doc.setTextColor(0);
  doc.text(new Date().toLocaleDateString("en-IN"), pageWidth - 40, y, { align: "right" });
  y += 34;
  doc.setDrawColor(210);
  doc.line(40, y, pageWidth - 40, y);
  y += 24;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(rupeeSafe(title), 40, y);
  y += 18;
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90);
    doc.text(rupeeSafe(subtitle), 40, y);
    doc.setTextColor(0);
    y += 18;
  }
  y += 6;

  if (summary.length) {
    const colW = (pageWidth - 80) / summary.length;
    summary.forEach((s, i) => {
      const x = 40 + i * colW;
      doc.setFontSize(8);
      doc.setTextColor(130);
      doc.text(rupeeSafe(s.label).toUpperCase(), x, y);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      if (s.color) doc.setTextColor(...s.color);
      doc.text(rupeeSafe(s.value), x, y + 14);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0);
    });
    y += 34;
  }

  autoTable(doc, {
    startY: y,
    head: [columns.map(c => rupeeSafe(c.label))],
    body: rows.map(r => columns.map(c => rupeeSafe(r[c.key] ?? "—"))),
    styles: { fontSize: 9, cellPadding: 6, overflow: "linebreak" },
    headStyles: { fillColor: [25, 25, 25], textColor: 255 },
    alternateRowStyles: { fillColor: [247, 247, 247] },
    columnStyles: columns.reduce(
      (acc, c, i) => (c.align === "right" ? { ...acc, [i]: { halign: "right", minCellWidth: 78 } } : acc),
      {}
    ),
    margin: { left: 40, right: 40 },
  });

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by BallMill ERP — Nova Geo Resources", 40, doc.internal.pageSize.getHeight() - 20);

  doc.save(fileName || `${title.replace(/[^\w]+/g, "_")}.pdf`);
}
